export { default as Request } from './Requests/Request.jsx'
export { default as Message } from './Messages/Message.jsx'
export { default as Payment } from './Payments/Payment.jsx'
export { default as Invoicing } from './Invoicing/Invoicing.jsx'
export { default as Settings } from './Settings/Settings.jsx'
export { default as Student } from './Students/Student.jsx'
export { default as Schedule } from './Schedule/schedule.jsx'
export { default as Dashboard } from './Dashboard/dasboard.jsx'
export {default as ClinicalSite} from './Clinical sites/ClinicalSite.jsx'
export  {default as School} from './School/School.jsx'
export { default as Sidebar } from './sidebar/sidebar.jsx'